disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- compiler_protocol_init
- multiple_closures_with_trailing_closure

excluded:
    - Pods

identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

line_length: 300

type_name:
  min_length: 2 # only warning

type_body_length:
  - 400 #warning
  - 500 #error

